
module Astro {

	interface DeviceLocator {
	};

	interface DriverModule {
		string	getName();
	};

	interface Modules {
		long	numberOfModules();
		typedef sequence<string> ModuleNameSequence;
		ModuleNameSequence	getModuleNames();
		DriverModule	getModule(in string name);
	};

};

