//
// guider.idl -- Interface to an autonomous guider
//
// (c) 2013 Prof Dr Andreas Mueller, Hochschule Rapperswil 2013
//
#include "camera.idl"

module Astro {
	/**
	 * \brief guiders are described by camera, ccdid and guider port
	 *
	 * Camera name and guiderport name are standard device URLs, the 
	 * ccdid is the number of the ccd.
	 */
	struct GuiderDescriptor {
		string	cameraname;
		long	ccdid;
		string	guiderportname;
	};

	/**
	 * \brief Interface for guiders
	 *
	 * Guiders take information from images shot through a ccd of a
	 * attached camera, and derive corrective actions that they then
	 * output to the guiderport.
	 */
	interface Guider {
		/**
		 * \brief States of the guider
		 */
		enum GuiderState {
			// Without the camera, ccd and guiderport selected,
			// the guider is not configured
			GUIDER_UNCONFIGURED,
			// When the camera, ccd and guider port have been
			// configured, the 
			GUIDER_IDLE,
			// Before the guider can be used for guiding, it must
			// be calibrated
			GUIDER_CALIBRATING,
			// When the guider ist calibrated, it can be used
			// for guiding
			GUIDER_CALIBRATED,
			// The calibrated guider can be used for guiding
			GUIDER_GUIDING
		};
		GuiderState	getState();

		/**
		 * \brief Get the camera that was chosen for the guider
		 */
		Camera	getCamera() raises(BadState);
		/**
		 * \brief Get the CCD that was chosen for the guider
		 */
		Ccd	getCcd() raises(BadState);
		
		/**
		 * \brief Choose a guider port for the guider
		 *
		 * If a string of length 0 is given as the name, then
		 * it is assumed that the guider port of the chosen
		 * camera should be used
		 */
		GuiderPort	getGuiderPort() raises(BadState);

		/**
		 * \brief return the descriptor that created the guider
		 */
		GuiderDescriptor	getDescriptor();

		// The guider needs to know how to expose an image, where
		// to look for the guide star and where to lock it.
		void	setExposure(in Exposure expo)
				raises(BadParameter,BadState);
		Exposure	getExposure();

		// This is the position of the star we want to track.
		// It does not have to be exact at the beginning, and
		// the position is only used as a reference point during 
		// calibration. During guiding, the guide star is kept
		// in this position.
		void	setStar(in Point star)
				raises(BadParameter,BadState);
		Point	getStar() raises(BadState);

		/**
		 * \brief Methods related to calibration
		 */
		struct Calibration {
			float	coefficients[6];
		};
		void	useCalibration(in Calibration cal);
		Calibration	getCalibration() raises(BadState);

		// methods to perform a calibration asynchronously
		void	startCalibration(in float focallength);
		double	calibrationProgress() raises(BadState);
		void	cancelCalibration() raises(BadState);
		boolean	waitCalibration(in double timeout) raises(BadState);

		// Start and stop the guding process.
		// Before this can be done, the exposure parameters must be
		// specified, as the determine which are of the CCD to read
		// out and where to look for the star and where to lock it
		void	startGuiding(in float guidinginterval) raises(BadState);
		float	getGuidingInterval() raises(BadState);
		void	stopGuiding() raises(BadState);

		// The following methods are used to monitor the calibration
		// or the guiding. The guider keeps the most recent image
		// so that a GUI application can fetch thosei mages and 
		// display them to the user
		/**
		 * \brief 
		 */
		Image	mostRecentImage() raises(BadState);
		/**
		 * \brief Information about recent tracking activities
		 */
		struct TrackingInfo {
			double	timeago;
			Point	trackingoffset;
			Point	activation;
		};
		TrackingInfo	mostRecentTrackingInfo()
						raises(BadState);
	};

	/**
	 * \brief The GuiderFactory builds Guider objects
	 *
	 * Guiders are persistent in the server, because the may have to be
	 * doing their work even when no client is connected. The GuiderFactory
	 * keeps a repository of guider objects. New guider objects can
	 * be created by specifying camera, ccd and guider port.
	 */
	interface GuiderFactory {
		typedef sequence<GuiderDescriptor> GuiderList;
		GuiderList	list();
		Guider	get(in GuiderDescriptor descriptor) raises(NotFound);
	};
};
