//
// module.idl -- Interface definition for modules
//
// (c) 2013 Prof Dr Andreas Mueller, Hochschule Rapperswil
//
#include "camera.idl"

/**
 * \brief Astro module captures all interfaces
 */
module Astro {
	// Module related stuff
	/**
	 * \brief Device Locator interface within a module
	 */
	interface DeviceLocator {
		string	getName();
		string	getVersion();
		typedef sequence<string>	DeviceNameList;
		enum device_type { DEVICE_CAMERA, DEVICE_FOCUSER,
					DEVICE_GUIDERPORT, DEVICE_FILTERWHEEL,
					DEVICE_COOLER };
		/**
		 * \brief Retrieve a list of device names for a device type
		 *
		 * Most camera drivers just give access to camera devices.
		 * But some devices may be accessed independently of a camera,
		 * e.g. the USB filterwheel from QHYCCD, which has it's own
		 * interface independent of a camera.
		 * \param devicetype	Type of device to construct the list
		 */
		DeviceNameList	getDevicelist(in device_type devicetype);
		Camera		getCamera(in string name) raises(NotFound);
		GuiderPort	getGuiderPort(in string name) raises(NotFound);
		FilterWheel	getFilterWheel(in string name) raises(NotFound);
		Cooler		getCooler(in string name) raises(NotFound);
		Focuser		getFocuser(in string name) raises(NotFound);
	};

	struct Descriptor {
		string name;
		string version;
		boolean hasDeviceLocator;
	};

	/**
	 * \brief Interface to driver modules
	 *
	 * A module may implement many other things but device access.
	 * To find out whether the module gives access to any devices,
	 * one should query the Descriptor and check whether the module
	 * implements a DeviceLocator. The DeviceLocator obtained from
	 * the getDeviceLocator() method can then be used to get the
	 * devices themselves.
	 */
	interface DriverModule {
		Descriptor	getDescriptor();
		string	getName();
		/**
		 * \brief Get the device locator of a module
		 */
		DeviceLocator	getDeviceLocator() raises(NotImplemented);
	};

	/**
	 * \brief Repository of all device driver modules
	 *
 	 * All device driver modules are accessible through this interface.
	 */
	interface Modules {
		long	numberOfModules();
		typedef sequence<string> ModuleNameSequence;
		ModuleNameSequence	getModuleNames();
		DriverModule	getModule(in string name) raises(NotFound);
	};
};

